### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by oxr463** [valkyrienyanko/Unity-MMORPG-Boilerplate#33]
See: https://www.atlassian.com/git/tutorials/monorepos

**Comment by valkyrienyanko** [comment]
The repo size is currently `5.03 MB`. The only thing that I can foresee that will grow in size is the Unity assets folder, but even then it wouldn't be that large.

I try to stay away from branch workflows as I've had bad experiences in the past with them. 

I'm going to hold off on splitting the repo into smaller repo's, this may involve creating a GitHub organization of some sorts which I'm unfamiliar with.

**Comment by valkyrienyanko** [comment]
@oxr463 I decided to go with your suggestion after all, thank you.
