### ISSUE TITLE
Support for Linux?

### ISSUE THREAD

**Issue by oxr463** [valkyrienyanko/Unity-MMORPG-Boilerplate#34]
> System requirements
>
> OS: Windows 7 SP1+, 8, 10, 64-bit versions only; Mac OS X 10.12+; Ubuntu 16.04, 18.04, and CentOS 7.
> --https://unity3d.com/get-unity/download

**Comment by valkyrienyanko** [comment]
Seems to be only supported in 2020 versions of Unity

https://blogs.unity3d.com/2019/05/30/announcing-the-unity-editor-for-linux/
